import { v4 as uuidv4 } from "uuid";

export const GHG_SEED_DATA = [
    // --- 2024 Scope 1 ---
    {
        id: uuidv4(),
        date: new Date("2024-01-15"),
        scope: 1,
        category: "Stationary Combustion (Genset/Boiler)",
        source: "diesel_inds",
        value: 1200,
        unit: "Liters",
        emissionFactor: 0.00268,
        co2e: 1200 * 0.00268,
        notes: "Genset operation for Main Office",
    },
    {
        id: uuidv4(),
        date: new Date("2024-02-10"),
        scope: 1,
        category: "Mobile Combustion (Company Vehicles)",
        source: "gasoline_veh",
        value: 850,
        unit: "Liters",
        emissionFactor: 0.00231,
        co2e: 850 * 0.00231,
        notes: "Logistics fleet fuel consumption",
    },
    // --- 2024 Scope 2 ---
    {
        id: uuidv4(),
        date: new Date("2024-03-05"),
        scope: 2,
        category: "Purchased Electricity (PLN Grid)",
        source: "pln_grid",
        value: 15400,
        unit: "kWh",
        emissionFactor: 0.00087,
        co2e: 15400 * 0.00087,
        notes: "Monthly factory power consumption",
    },
    // --- 2024 Scope 3 ---
    {
        id: uuidv4(),
        date: new Date("2024-04-12"),
        scope: 3,
        category: "Business Travel (Flights)",
        source: "flight_eco",
        value: 4500,
        unit: "km",
        emissionFactor: 0.00015,
        co2e: 4500 * 0.00015,
        notes: "Regional management site visit",
    },
    {
        id: uuidv4(),
        date: new Date("2024-05-20"),
        scope: 3,
        category: "Waste Disposal",
        source: "waste_landfill",
        value: 12,
        unit: "tons",
        emissionFactor: 0.450,
        co2e: 12 * 0.450,
        notes: "General solid waste disposal",
    },
    // --- 2025 Recent Data (Intensity Heatmap) ---
    {
        id: uuidv4(),
        date: new Date("2025-01-01"),
        scope: 1,
        category: "Stationary Combustion (Genset/Boiler)",
        source: "diesel_inds",
        value: 2500,
        unit: "Liters",
        emissionFactor: 0.00268,
        co2e: 2500 * 0.00268,
        notes: "New Year power backup",
    },
    {
        id: uuidv4(),
        date: new Date("2025-02-14"),
        scope: 2,
        category: "Purchased Electricity (PLN Grid)",
        source: "pln_grid",
        value: 20000,
        unit: "kWh",
        emissionFactor: 0.00087,
        co2e: 20000 * 0.00087,
        notes: "High production cycle electricity",
    }
];
